
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - redhatcop.my.domain
  resources:
  - patches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.my.domain
  resources:
  - patches/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.my.domain
  resources:
  - patches/status
  verbs:
  - get
  - patch
  - update
